FROM python:3.6

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "uwsgi", "uwsgi.ini", "--py-auto-reload", "1", "--worker-reload-mercy", "5" ]
